docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
site_name: laminas-mvc-plugin-identity
site_description: 'laminas-mvc-plugin-identity: Retrieve the current authenticated identity within a laminas-mvc controller'
repo_url: 'https://github.com/laminas/laminas-mvc-plugin-identity'
